### ISSUE TITLE
[Theme] RefinementList items labels don't wrap nicely

### ISSUE THREAD

**Issue by olance** [algolia/react-instantsearch#133]
When there isn't enough space to have refinement list labels displayed on a single line, the text and facet counts both wrap under the checkbox in a not-so-stylish fashion:

<img src="https://user-images.githubusercontent.com/314079/27306119-bcd85736-5544-11e7-99ad-3823aca7d299.png" width="285">

I propose the use of `flexbox` for a nicer rendering:

<img src="https://user-images.githubusercontent.com/314079/27306149-db5bc378-5544-11e7-8b67-c8db3ab6c148.png" width="285">

Here are the changes I made:

```css
.ais-RefinementList__item label {
    display: flex;
}

.ais-RefinementList__itemCount {
    align-self: baseline;
}

.ais-RefinementList__item .ais-RefinementList__itemBox {
    flex-grow: 0;
    flex-shrink: 0;
}

.ais-RefinementList__itemLabel {
    flex-grow: 1;
}
```

wdyt @LukyVj ?
