### ISSUE TITLE
Load More Button Issue

### ISSUE THREAD

**Issue by t-lochhead** [algolia/react-instantsearch#2966]
I'm on MacOS, desktop, Chrome. When I click the load more button for an infinite hits search results, the search results get pushed down (expected behavior), until results fill the screen. At that point, results get pushed up (undesired behavior).

It works fine in Safari and in Chrome on my iPhone.

I am able to reproduce the issue with this link: https://instantsearchjs.netlify.app/stories/?path=/story/results-infinitehits--default

Here is a video of the error:
https://www.youtube.com/watch?v=klojPCGMY8A

**Comment by Haroenv** [comment]
This is a "bug" / "feature" in Google Chrome (bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1110323#c1) which has been fixed in InstantSearch.css v7.4.3 with the following workaround (which you can also add without updating):

```css
// Prevent InfiniteHits buttons from moving scroll position
 // https://bugs.chromium.org/p/chromium/issues/detail?id=1110323
 .ais-InfiniteHits-loadPrevious,
 .ais-InfiniteHits-loadMore {
   overflow-anchor: none;
 }
```
